---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - appliances.home.sijoma.dev
  resources:
  - coffeemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appliances.home.sijoma.dev
  resources:
  - coffeemachines/finalizers
  verbs:
  - update
- apiGroups:
  - appliances.home.sijoma.dev
  resources:
  - coffeemachines/status
  verbs:
  - get
  - patch
  - update
