apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../config/default
- mosquitto/

patchesStrategicMerge:
- manager-patch.yaml
images:
- name: controller
  newName: controller
  newTag: latest
